### ISSUE TITLE
Already referencing a newer version of 'NHibernate'

### ISSUE THREAD

**Issue by thirupathicst** [TheCloudlessSky/Harbour.RedisSessionStateStore#33]
i'm using VS2012 MVC 4 when i'm install Install-Package BetterCMS pakage i'm get this error
Install-Package : Already referencing a newer version of 'NHibernate'.
At line:1 char:16
- Install-Package <<<<  BetterCMS
  - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by TheCloudlessSky** [comment]
Hey @thirupathicst - you're going to have to talk to the BetterCMS team since I don't know anything about BetterCMS. Your error doesn't seem like it has anything to do with `Harbour.RedisSessionStateStore`. If you can make a small reproducible case for just this library, I'll be glad to help out (and re-open this issue).
